language: android
android:
  components:
    - build-tools-29.0.2
    - android-29
    - sys-img-armeabi-v7a-android-29
    - sys-img-x86-android-29

before_script:
  - chmod +x gradlew

script:
  - ./gradlew :app:assembleRelease
